version: "3.9"

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: kltn
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: dinhthi2509/kltn-backend:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5235:8080"
    environment:
      - ConnectionStrings__Default=server=mysql;port=3306;database=kltn;user=root;password=${MYSQL_ROOT_PASSWORD}

  frontend:
    image: dinhthi2509/kltn-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: